name: Docker

on:
  schedule:
    - cron: '44 2 * * *'
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
    paths-ignore:
      - '**.md'  # Ignore readme changes
      - '**.yml'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'  # Ignore readme changes
      - '**.yml'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual trigger'
        required: false
        default: 'Manual build'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: qincai-rui/poker-over-ssh

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout Poker-over-SSH source
        uses: actions/checkout@v4
        with:
          repository: poker-ssh/Poker-over-SSH
          path: Poker-over-SSH
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1

      # Setup QEMU for multi-architecture builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Setup Docker Buildx with explicit driver configuration
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:latest

      # Verify the builder is correctly configured
      - name: Inspect builder
        run: |
          echo "Name: ${{ steps.buildx.outputs.name }}"
          echo "Driver: ${{ steps.buildx.outputs.driver }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      # Login to registry
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata for Docker
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=raw,value=latest

      # Build and push Docker image
      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Install cosign for signing
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.3.0

      # Sign the published Docker image
      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' && steps.build-and-push.outputs.digest != '' }}
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: |
          echo "Digest: ${DIGEST}"
          echo "Tags: ${TAGS}"
          if [ -n "${DIGEST}" ]; then
            echo "${TAGS}" | xargs -I {} cosign sign --yes "{}@${DIGEST}"
          else
            echo "Digest is empty, skipping signing"
          fi